### ISSUE TITLE
Can't make it work =(

### ISSUE THREAD

**Issue by AnimeDrache** [SirLeezus/NameColors#2]
Greetings,

I am using EssentialsX + Luckperms but I really can't make this work. I gave all permissions to everyone, did restarts etc. but still can't make the hearts (life) visible or change any color in the hovering name on top of the players.

I appreciate your support ♥!

**Comment by LeeTheTech** [comment]
I would suggest using: https://www.spigotmc.org/resources/nametagedit.3836/ I'm no longer working on this plugin and if I were to re-do it the plugin would just look like nametagedit, packets are in fact the best option when it comes to this.

**Comment by AnimeDrache** [comment]
Thank you for answering me and also thank you for the link! That's exactly what I was looking for when I found your plugin hehe! ♥
